---
- name: Configure apache2
  hosts: all
  tasks:
    - name: Install apache2
      apt:
        name: apache2
        state: present
        update_cache: yes
    - name: Edit the index.html file
      copy:
        content: "The Zabi world"
        dest: /var/www/html/index.html
    - name: Restart apache2
      service:
        name: apache2
        state: restarted
    - name: Check apcahe on server1
      uri:
        url: http://172.31.16.75
        status_code: 200
    - name: Check apache on server2
      uri:
        url: http://172.31.27.220
        status_code: 200
...
